#开发环境
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ipcis_nvhlclm?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: axtest
    password: 'axtest123'
    #url: jdbc:mysql://10.10.8.2:3306/claimdb?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    #username: axclaim
    #password: 'cxIIy890'
    driver-class-name: com.mysql.jdbc.Driver
    maximum-pool-size: 15
    #测试库连接超时时间过短，需要将存活时间调低
    #连接最大生存时间，连接创建后最大的存活时间，active/idle 时间都算存活时间，跟idle-time不同（使用中的连接不会被移除）
    #max-lifetime需要比idle-timeout大1s以上
    #默认1800000ms，最低30000ms，若低于最低值会被重置为默认值
    max-lifetime: 1800000
    #默认600000ms，最低10000ms，若低于最低值会被重置为默认值
    idle-timeout: 600000
  servlet:
  multipart:
    max-file-size: 2MB

neo4j:
  datasource:
    url: jdbc:neo4j:bolt://localhost:7687
    #url: jdbc:neo4j:bolt://10.0.0.219:7687
    username: neo4j
    password: 'remark'
    driver-class-name: org.neo4j.jdbc.Driver
    maximum-pool-size: 15
    #测试库连接超时时间过短，需要将存活时间调低
    #连接最大生存时间，连接创建后最大的存活时间，active/idle 时间都算存活时间，跟idle-time不同（使用中的连接不会被移除）
    #max-lifetime需要比idle-timeout大1s以上
    #默认1800000ms，最低30000ms，若低于最低值会被重置为默认值
    max-lifetime: 1800000
    #默认600000ms，最低10000ms，若低于最低值会被重置为默认值
    idle-timeout: 600000

rangeUrl: http://10.0.0.25:8765/uncar/claim/form/csv/downloadData/range/
#rangeUrl: http://10.6.6.118:8765/uncar/claim/form/csv/downloadData/range/
